### ISSUE TITLE
Import failed, DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by fj11** [rigglemania/pysqlcipher3#17]
When import pysqlcipher3, it failed because of DLL load failed. 

Python version 3.7.1

Pyd file is at: C:\Python37\Lib\site-packages\pysqlcipher3-1.0.2-py3.7-win32.egg\pysqlcipher3\_sqlite3.cp37-win32.pyd

Traceback (most recent call last):
  File "C:/Python37/Lib/site-packages/pysqlcipher3-1.0.2-py3.7-win32.egg/pysqlcipher3/_sqlite3.py", line 9, in <module>
    __bootstrap__()
  File "C:/Python37/Lib/site-packages/pysqlcipher3-1.0.2-py3.7-win32.egg/pysqlcipher3/_sqlite3.py", line 8, in __bootstrap__
    imp.load_dynamic(__name__,__file__)
  File "C:\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

**Comment by pouyamiralayi** [comment]
Hello there! i have the similar error output:
 from pysqlcipher3._sqlite3 import *
ImportError: DLL load failed: The specified module could not be found.

i inspect the _sqlite3.pyd and it seems missing libeay32.dll and msvcr90.dll but providing these libraries inside system32 does not solve the problem.

i built pysqlcipher3 against system libsqlcipher and the built was fine.
i am in a conda environment tested both on py3.7 and py3.6 as well.

thanks in advance.
