### ISSUE TITLE
ImportError when import dbapi2

### ISSUE THREAD

**Issue by xilihuasi** [rigglemania/pysqlcipher3#27]
- Step 1
   `pip install pysqlcipher3`
- Step2
    edit `from pysqlcipher3 import dbapi2 as sqlite` in my python file `decrypt-db.py`

Then, it will throw error

```shell
Traceback (most recent call last):
  File "/Users/macos/workspace/decrypt-db.py", line 12, in <module>
    from pysqlcipher3 import dbapi2 as sqlite
  File "Library/Python/3.8/lib/python/site-packages/pysqlcipher3/dbapi2.py", line 33, in <module>
    from pysqlcipher3._sqlite3 import *
ImportError: dlopen(/Library/Python/3.8/lib/python/site-packages/pysqlcipher3/_sqlite3.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_sqlite3_enable_load_extension'
```

- System Version: macOS Montery
- Python Version: 3.8.9

**Comment by zscFirefly** [comment]
@xilihuasi Hi, I have same problem, and I want to know how do you deal with it.

**Comment by anyboywhose** [comment]
> @xilihuasi Hi, I have same problem, and I want to know how do you deal with it.
When you have compiled sqlcipher,you need to recompile libsqlcipher.a! 
That is to say,ar -x libsqlcipher.a,then ar -x libcrypto.a,last ar -r libsqlcipher.a *.o.
when you get a new libsqlcipher.a,download pysqlcipher3 source and python3 setup.py build.
if this answer help you,please call me "uncle Leifeng"
