### ISSUE TITLE
Why it automatically remove all file after installed

### ISSUE THREAD

**Issue by Seraphli** [rigglemania/pysqlcipher3#7]
I was trying to install using pip, and after it showed `Successfully installed pysqlcipher3`, it removed the package every time. I don't know why.

**Comment by Seraphli** [comment]
And I tried to download zip file from github and manually installed it. Same situation happened.

**Comment by rigglemania** [comment]
My initial thought is that this is an issue with your environment given this code hasn't changed in months and no one else has reported similar problems. And what does "removing the package" mean exactly? You'll have to provide more specific details to help me understand.

**Comment by Seraphli** [comment]
I was wondering the same thing. The thing happens in this way:
1. Pip would download the package
2. Pip would extract the package and install on the computer. I can clearly see the egg-info appear in the "Everything", a file searching tool.
3. Then when the terminal displayed "Successful install....". The package disappeared from Everything.

**Comment by rigglemania** [comment]
I don't know anything about "Everything", so if there's any issues with that tool, I can't be of help there. Maybe you are looking at the wrong installed location or maybe you looking at an intermediate build output that then gets removed once the final artifact is built.

**Comment by Seraphli** [comment]
There is nothing to do with "Everything". I assume some dependencies are missing on my PC, but the installation doesn't know about it. So after installed, the package is simply broken and can not be used. So pip deletes the package without displaying any error. Maybe it happened because I hadn't compiled sqlite or sqlcipher.

**Comment by rigglemania** [comment]
The only other thing I could think of that might prove helpful would be running pip install in verbose mode (--verbose)

**Comment by Seraphli** [comment]
-> pip install pysqlcipher3 --verbose
```
Collecting pysqlcipher3
  1 location(s) to search for versions of pysqlcipher3:
  * https://pypi.python.org/simple/pysqlcipher3/
  Getting page https://pypi.python.org/simple/pysqlcipher3/
  Looking up "https://pypi.python.org/simple/pysqlcipher3/" in the cache
  Current age based on date: 1224685
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The cached response is "stale" with no etag, purging
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/pysqlcipher3/ HTTP/1.1" 200 309
  Updating cache with response from "https://pypi.python.org/simple/pysqlcipher3
/"
  Caching b/c date exists and max-age > 0
  Analyzing links from page https://pypi.python.org/simple/pysqlcipher3/
    Found link https://pypi.python.org/packages/96/82/105fa83608956f0f4270534845
dd4683eba548eacee371ccc01dab7a8856/pysqlcipher3-1.0.2.tar.gz#md5=387aa1f10ff84b7
2d879c111c6fce3d7 (from https://pypi.python.org/simple/pysqlcipher3/), version:
1.0.2
    Found link https://pypi.python.org/packages/f8/6a/37b2e468a9a48704fc807df64b
2b2b86b446dad781adfdf7f221a972674e/pysqlcipher3-1.0.1.tar.gz#md5=9ef29fbe149391b
574f5c2a08d188e43 (from https://pypi.python.org/simple/pysqlcipher3/), version:
1.0.1
  Using version 1.0.2 (newest of versions: 1.0.1, 1.0.2)
  Looking up "https://pypi.python.org/packages/96/82/105fa83608956f0f4270534845d
d4683eba548eacee371ccc01dab7a8856/pysqlcipher3-1.0.2.tar.gz" in the cache
  Current age based on date: 1224686
  Freshness lifetime from max-age: 31557600
  The response is "fresh", returning cached response
  31557600 > 1224686
  Using cached pysqlcipher3-1.0.2.tar.gz
  Downloading from URL https://pypi.python.org/packages/96/82/105fa83608956f0f42
70534845dd4683eba548eacee371ccc01dab7a8856/pysqlcipher3-1.0.2.tar.gz#md5=387aa1f
10ff84b72d879c111c6fce3d7 (from https://pypi.python.org/simple/pysqlcipher3/)
  Running setup.py (path:C:\Users\SERAPH~1\AppData\Local\Temp\pip-build-vqy0vbwd
\pysqlcipher3\setup.py) egg_info for package pysqlcipher3
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info\pysqlcipher3.egg-info
    writing top-level names to pip-egg-info\pysqlcipher3.egg-info\top_level.txt
    writing dependency_links to pip-egg-info\pysqlcipher3.egg-info\dependency_li
nks.txt
    writing pip-egg-info\pysqlcipher3.egg-info\PKG-INFO
    writing manifest file 'pip-egg-info\pysqlcipher3.egg-info\SOURCES.txt'
    reading manifest file 'pip-egg-info\pysqlcipher3.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*~' found anywhere in distri
bution
    warning: no previously-included files matching '*.pyc' found anywhere in dis
tribution
    writing manifest file 'pip-egg-info\pysqlcipher3.egg-info\SOURCES.txt'
  Source in c:\users\seraph~1\appdata\local\temp\pip-build-vqy0vbwd\pysqlcipher3
 has version 1.0.2, which satisfies requirement pysqlcipher3 from https://pypi.p
ython.org/packages/96/82/105fa83608956f0f4270534845dd4683eba548eacee371ccc01dab7
a8856/pysqlcipher3-1.0.2.tar.gz#md5=387aa1f10ff84b72d879c111c6fce3d7
Building wheels for collected packages: pysqlcipher3
  Running setup.py bdist_wheel for pysqlcipher3 ...   Destination directory: C:\
Users\SERAPH~1\AppData\Local\Temp\tmp5tjm_c2mpip-wheel-
  Running command d:\software\python\python35\python.exe -u -c "import setuptool
s, tokenize;__file__='C:\\Users\\SERAPH~1\\AppData\\Local\\Temp\\pip-build-vqy0v
bwd\\pysqlcipher3\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file
__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d C:\Users\SE
RAPH~1\AppData\Local\Temp\tmp5tjm_c2mpip-wheel- --python-tag cp35
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.5
  creating build\lib.win-amd64-3.5\pysqlcipher3
  copying lib\dbapi2.py -> build\lib.win-amd64-3.5\pysqlcipher3
  copying lib\dump.py -> build\lib.win-amd64-3.5\pysqlcipher3
  copying lib\__init__.py -> build\lib.win-amd64-3.5\pysqlcipher3
  creating build\lib.win-amd64-3.5\pysqlcipher3\test
  copying lib\test\__init__.py -> build\lib.win-amd64-3.5\pysqlcipher3\test
  creating build\lib.win-amd64-3.5\pysqlcipher3\test\python3
  copying lib\test\python3\dbapi.py -> build\lib.win-amd64-3.5\pysqlcipher3\test
\python3
  copying lib\test\python3\dump.py -> build\lib.win-amd64-3.5\pysqlcipher3\test\
python3
  copying lib\test\python3\factory.py -> build\lib.win-amd64-3.5\pysqlcipher3\te
st\python3
  copying lib\test\python3\hooks.py -> build\lib.win-amd64-3.5\pysqlcipher3\test
\python3
  copying lib\test\python3\regression.py -> build\lib.win-amd64-3.5\pysqlcipher3
\test\python3
  copying lib\test\python3\sqlcipher.py -> build\lib.win-amd64-3.5\pysqlcipher3\
test\python3
  copying lib\test\python3\transactions.py -> build\lib.win-amd64-3.5\pysqlciphe
r3\test\python3
  copying lib\test\python3\types.py -> build\lib.win-amd64-3.5\pysqlcipher3\test
\python3
  copying lib\test\python3\userfunctions.py -> build\lib.win-amd64-3.5\pysqlciph
er3\test\python3
  copying lib\test\python3\__init__.py -> build\lib.win-amd64-3.5\pysqlcipher3\t
est\python3
  running build_ext
  Builds a C extension linking against libsqlcipher library
  building 'pysqlcipher3._sqlite3' extension
  creating build\temp.win-amd64-3.5
  creating build\temp.win-amd64-3.5\Release
  creating build\temp.win-amd64-3.5\Release\src
  creating build\temp.win-amd64-3.5\Release\src\python3
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c
 /nologo /Ox /W3 /GL /DNDEBUG /MD -DMODULE_NAME=\"pysqlcipher3.dbapi2\" -I/usr/i
nclude:/usr/include/sqlcipher -Id:\software\python\python35\include -Id:\softwar
e\python\python35\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0
\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\IN
CLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC
:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program File
s (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits
\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" /Tc
src\python3\module.c /Fobuild\temp.win-amd64-3.5\Release\src\python3\module.obj
  module.c
  c:\users\seraph-li\appdata\local\temp\pip-build-vqy0vbwd\pysqlcipher3\src\pyth
on3\connection.h(33): fatal error C1083: Cannot open include file: 'sqlite3.h':
No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN
\\x86_amd64\\cl.exe' failed with exit status 2
done
  Running setup.py clean for pysqlcipher3
  Running command d:\software\python\python35\python.exe -u -c "import setuptool
s, tokenize;__file__='C:\\Users\\SERAPH~1\\AppData\\Local\\Temp\\pip-build-vqy0v
bwd\\pysqlcipher3\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file
__).read().replace('\r\n', '\n'), __file__, 'exec'))" clean --all
  running clean
  removing 'build\temp.win-amd64-3.5' (and everything under it)
  removing 'build\lib.win-amd64-3.5' (and everything under it)
  'build\bdist.win-amd64' does not exist -- can't clean it
  'build\scripts-3.5' does not exist -- can't clean it
  removing 'build'
Failed to build pysqlcipher3
Installing collected packages: pysqlcipher3
  Running setup.py install for pysqlcipher3 ...     Running command d:\software\
python\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\User
s\\SERAPH~1\\AppData\\Local\\Temp\\pip-build-vqy0vbwd\\pysqlcipher3\\setup.py';e
xec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n
'), __file__, 'exec'))" install --record C:\Users\SERAPH~1\AppData\Local\Temp\pi
p-5np67gg4-record\install-record.txt --single-version-externally-managed --compi
le
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.5
    creating build\lib.win-amd64-3.5\pysqlcipher3
    copying lib\dbapi2.py -> build\lib.win-amd64-3.5\pysqlcipher3
    copying lib\dump.py -> build\lib.win-amd64-3.5\pysqlcipher3
    copying lib\__init__.py -> build\lib.win-amd64-3.5\pysqlcipher3
    creating build\lib.win-amd64-3.5\pysqlcipher3\test
    copying lib\test\__init__.py -> build\lib.win-amd64-3.5\pysqlcipher3\test
    creating build\lib.win-amd64-3.5\pysqlcipher3\test\python3
    copying lib\test\python3\dbapi.py -> build\lib.win-amd64-3.5\pysqlcipher3\te
st\python3
    copying lib\test\python3\dump.py -> build\lib.win-amd64-3.5\pysqlcipher3\tes
t\python3
    copying lib\test\python3\factory.py -> build\lib.win-amd64-3.5\pysqlcipher3\
test\python3
    copying lib\test\python3\hooks.py -> build\lib.win-amd64-3.5\pysqlcipher3\te
st\python3
    copying lib\test\python3\regression.py -> build\lib.win-amd64-3.5\pysqlciphe
r3\test\python3
    copying lib\test\python3\sqlcipher.py -> build\lib.win-amd64-3.5\pysqlcipher
3\test\python3
    copying lib\test\python3\transactions.py -> build\lib.win-amd64-3.5\pysqlcip
her3\test\python3
    copying lib\test\python3\types.py -> build\lib.win-amd64-3.5\pysqlcipher3\te
st\python3
    copying lib\test\python3\userfunctions.py -> build\lib.win-amd64-3.5\pysqlci
pher3\test\python3
    copying lib\test\python3\__init__.py -> build\lib.win-amd64-3.5\pysqlcipher3
\test\python3
    running build_ext
    Builds a C extension linking against libsqlcipher library
    building 'pysqlcipher3._sqlite3' extension
    creating build\temp.win-amd64-3.5
    creating build\temp.win-amd64-3.5\Release
    creating build\temp.win-amd64-3.5\Release\src
    creating build\temp.win-amd64-3.5\Release\src\python3
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe
/c /nologo /Ox /W3 /GL /DNDEBUG /MD -DMODULE_NAME=\"pysqlcipher3.dbapi2\" -I/usr
/include:/usr/include/sqlcipher -Id:\software\python\python35\include -Id:\softw
are\python\python35\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14
.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\
INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-
IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Fi
les (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Ki
ts\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" /
Tcsrc\python3\module.c /Fobuild\temp.win-amd64-3.5\Release\src\python3\module.ob
j
    module.c
    c:\users\seraph-li\appdata\local\temp\pip-build-vqy0vbwd\pysqlcipher3\src\py
thon3\connection.h(33): fatal error C1083: Cannot open include file: 'sqlite3.h'
: No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\B
IN\\x86_amd64\\cl.exe' failed with exit status 2
done
  Record file C:\Users\SERAPH~1\AppData\Local\Temp\pip-5np67gg4-record\install-r
ecord.txt not found
  Removing source in C:\Users\SERAPH~1\AppData\Local\Temp\pip-build-vqy0vbwd\pys
qlcipher3
Successfully installed pysqlcipher3
Cleaning up...
There was an error checking the latest version of pip
Traceback (most recent call last):
  File "d:\software\python\python35\lib\site-packages\pip\utils\outdated.py", li
ne 117, in pip_version_check
    SELFCHECK_DATE_FMT
  File "d:\software\python\python35\lib\_strptime.py", line 277, in <module>
    _TimeRE_cache = TimeRE()
  File "d:\software\python\python35\lib\_strptime.py", line 194, in __init__
    self.locale_time = LocaleTime()
  File "d:\software\python\python35\lib\_strptime.py", line 73, in __init__
    self.__calc_weekday()
  File "d:\software\python\python35\lib\_strptime.py", line 95, in __calc_weekda
y
    a_weekday = [calendar.day_abbr[i].lower() for i in range(7)]
  File "d:\software\python\python35\lib\_strptime.py", line 95, in <listcomp>
    a_weekday = [calendar.day_abbr[i].lower() for i in range(7)]
  File "d:\software\python\python35\lib\calendar.py", line 79, in __getitem__
    return funcs(self.format)
ValueError: embedded null byte
```

**Comment by Seraphli** [comment]
So it's true. The error was caused by `sqlite3.h`, and you can notice it still display `Successfully installed pysqlcipher3` after the error.

**Comment by rigglemania** [comment]
As stated in the install instructions, "Prior to installation, libsqlcipher must already be installed on your system, with the process dependent on your operating system."
